### ISSUE TITLE
[Best Practice] Beware of liquid whitespace control ;)

### ISSUE THREAD

**Issue by OCram85** [tschwaerzl/tschwaerzl.github.io#1]
https://shopify.github.io/liquid/basics/whitespace/

**Comment by tschwaerzl** [comment]
Ha! :smile: I knew of that "issue", but where did I screw it up? :eyes:

**Comment by OCram85** [comment]
You just didn't use the `-` to remove the whitespaces :smile_cat:

**Comment by tschwaerzl** [comment]
In raw HTML there are whitespaces, true - but nothing visible on the users browser side. At least I didn't find any wrong output with false whitespaces.

If you think of reducing load times by reducing the whitespaces, then I think there are many more issues on that template :slightly_frowning_face: that need to be fixed.

**Comment by OCram85** [comment]
Sure - Just switch to [beautiful-jekyll](https://github.com/daattali/beautiful-jekyll) :+1:

**Comment by tschwaerzl** [comment]
Thanks for this one. :+1: 
Now I see how you got into the whitespace issue thinking. Right now _beautiful-jekyll_ isn't the thing I'm looking for. I like the almost "super minimal" approach of my current theme. Maybe I'll switch some time in the future, but for now I'm going to reduce the `margin` in CSS to get rid of the big white areas.

**Comment by OCram85** [comment]
Damn - I hoped you suggest starting a new theme based on [materializecss](https://getbootstrap.com/) or [](http://materializecss.com/)
